config/routes.rb
Imageretriver::Application.routes.draw do
  resources :posts

   root 'posts#index'
   post 'posts/:id/search' => 'posts#search', :as => :search_post
   

end

app/models/post.rb
class Post < ActiveRecord::Base

	has_attached_file :image, styles: { large: "600x600>",medium: "600x600>", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
 	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
require 'phashion'
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    
    @post = Post.find(params[:id])
    @similarpost = Array.new
    @posts = Post.all
    img = Phashion::Image.new @post.image.path(:medium)
    
    @posts.each do |p|
      tmpimg = Phashion::Image.new p.image.path(:medium)
      if(img.distance_from(tmpimg)< 100 and !img.duplicate?(tmpimg, :threshold => 0))
        @similarpost.push p
      end    
    end 
  end
  
  def search
    @posts = Post.all
    @post = Post.find((params[:id]))
    @pos_im = Array.new
    @newimage = Array.new
    sumfingerprint = 0
    #@post.positive_images.each do f
    imgparams = params['post']['positive_images']
    imgparams.each do |f|
      
      @pos_im.push Post.find(f.to_i)
    end
    img = Phashion::Image.new @post.image.path(:medium)
    @pos_im.each do |p|
      tmpimg = Phashion::Image.new p.image.path(:medium)
      sumfingerprint = sumfingerprint + tmpimg.fingerprint 
    end
      avfingerprint = 0.2 * sumfingerprint + 0.8 * img.fingerprint / imgparams.length + 1
      @posts.each do |p|
      tmp = Phashion::Image.new p.image.path(:medium)
      if(Phashion.hamming_distance(tmp.fingerprint,avfingerprint)< 29 and !tmp.duplicate? img )
        @newimage.push p
      end    
    end 
      #@pos_im.push tmp
    
    
  end


  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content,:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imageretriver</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post,html:{multipart: true} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= image_tag post.image.url(:thumb) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Upload new Image', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/search.html.erb
<p id="notice"><%= notice %></p>

  
  <%= image_tag @post.image.url(:medium) %>
  <h1>Positive FeedBack</h1>
  <br/>
  <br/>
  <br/>
  <% @newimage.each do |p|%>

<p><%= image_tag p.image.url(:medium)  %></p>
<%end%>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

  
  <%= image_tag @post.image.url(:medium) %>
  <br/>
  <br/>
  <br/>
  <h1>Similar Images</h1>
<%= form_tag search_post_path, :method => :post  do    %>	
<% @similarpost.each do |p|%>

<p><%= image_tag p.image.url(:medium)  %></p>
<%= check_box_tag "post[positive_images][]",p.id,false,:id =>p.id %>
<%= label_tag("Like") %>

<% end%>
<br></br>
<%= submit_tag "Recall"%>
<%end%>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>